_wandb:
    value:
        cli_version: 0.18.1
        m:
            - "1": gradients/linear.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": gradients/linear.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": parameters/linear.weight.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": parameters/linear.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": parameters/linear.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": parameters/linear.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/linear.bias.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/linear.bias.bins
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/linear.weight._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gradients/linear.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": parameters/linear.weight.values
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": parameters/linear.bias._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 55
                - 63
                - 74
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 55
                - 63
                - 74
                - 103
            "3":
                - 1
                - 2
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.12.3
            "5": 0.18.1
            "8":
                - 3
                - 5
            "12": 0.18.1
            "13": windows-amd64
bias:
    value: true
input_dim:
    value: 512
l1_strength:
    value: 0
l2_strength:
    value: 0
learning_rate:
    value: 0.0001
optimizer:
    value: Adam
output_dim:
    value: 1
